//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monopoly.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Board.
        /// </summary>
        internal static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        internal static string chance {
            get {
                return ResourceManager.GetString("chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled Roll.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        internal static string endTurn {
            get {
                return ResourceManager.GetString("endTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string magProper {
            get {
                return ResourceManager.GetString("magProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1.
        /// </summary>
        internal static string p1Label {
            get {
                return ResourceManager.GetString("p1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2.
        /// </summary>
        internal static string p2Label {
            get {
                return ResourceManager.GetString("p2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Fine.
        /// </summary>
        internal static string payFine {
            get {
                return ResourceManager.GetString("payFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string roll {
            get {
                return ResourceManager.GetString("roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income\r\nTax.
        /// </summary>
        internal static string taxLabel {
            get {
                return ResourceManager.GetString("taxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        internal static string trade {
            get {
                return ResourceManager.GetString("trade", resourceCulture);
            }
        }

        internal static string NumOfPlayers {
            get
            {
                return ResourceManager.GetString("NumOfPlayers", resourceCulture);
            }
        }

        internal static string twoPlayers {
            get
            {
                return ResourceManager.GetString("twoPlayers", resourceCulture);
            }
        }

        internal static string threePlayers{
            get
            {
                return ResourceManager.GetString("threePlayers", resourceCulture);
            }

        }

        internal static string fourPlayers
        {
            get
            {
                return ResourceManager.GetString("fourPlayers", resourceCulture);
            }

        }
        internal static string confirm
        {
            get
            {
                return ResourceManager.GetString("confirm", resourceCulture);
            }

        }
        internal static string enterPlayerName
        {
            get
            {
                return ResourceManager.GetString("enterPlayerName", resourceCulture);
            }

        }
        internal static string controlBoard
        {
            get
            {
                return ResourceManager.GetString("controlBoard", resourceCulture);
            }

        }
        internal static string selectProperty
        {
            get
            {
                return ResourceManager.GetString("selectProperty", resourceCulture);
            }

        }
        internal static string tradePrice
        {
            get
            {
                return ResourceManager.GetString("tradePrice", resourceCulture);
            }

        }
        internal static string cancel
        {
            get
            {
                return ResourceManager.GetString("cancel", resourceCulture);
            }

        }
        internal static string message1
        {
            get
            {
                return ResourceManager.GetString("message1", resourceCulture);
            }

        }
        internal static string player1Trade
        {
            get
            {
                return ResourceManager.GetString("player1Trade", resourceCulture);
            }

        }
        internal static string player2Trade
        {
            get
            {
                return ResourceManager.GetString("player2Trade", resourceCulture);
            }

        }
        internal static string message2
        {
            get
            {
                return ResourceManager.GetString("message2", resourceCulture);
            }

        }
        internal static string message3_1
        {
            get
            {
                return ResourceManager.GetString("message3_1", resourceCulture);
            }

        }
        internal static string message3_2
        {
            get
            {
                return ResourceManager.GetString("message3_2", resourceCulture);
            }

        }
        internal static string message4
        {
            get
            {
                return ResourceManager.GetString("message4", resourceCulture);
            }

        }
        internal static string message5
        {
            get
            {
                return ResourceManager.GetString("message5", resourceCulture);
            }

        }
        internal static string morgage
        {
            get
            {
                return ResourceManager.GetString("morgage", resourceCulture);
            }

        }
        internal static string buyHouse
        {
            get
            {
                return ResourceManager.GetString("buyHouse", resourceCulture);
            }

        }
        internal static string selectAll
        {
            get
            {
                return ResourceManager.GetString("selectAll", resourceCulture);
            }

        }
        internal static string deselectAll
        {
            get
            {
                return ResourceManager.GetString("deselectAll", resourceCulture);
            }

        }
        internal static string go
        {
            get
            {
                return ResourceManager.GetString("go", resourceCulture);
            }

        }
        internal static string freeParking
        {
            get
            {
                return ResourceManager.GetString("freeParking", resourceCulture);
            }

        }
        internal static string marvinGardens
        {
            get
            {
                return ResourceManager.GetString("marvinGardens", resourceCulture);
            }

        }
        internal static string ventnorAvenue
        {
            get
            {
                return ResourceManager.GetString("ventnorAvenue", resourceCulture);
            }

        }
        internal static string illinoisAvenue
        {
            get
            {
                return ResourceManager.GetString("illinoisAvenue", resourceCulture);
            }

        }
        internal static string indianaAvenue
        {
            get
            {
                return ResourceManager.GetString("indianaAvenue", resourceCulture);
            }

        }
        internal static string newYorkAvenue
        {
            get
            {
                return ResourceManager.GetString("newYorkAvenue", resourceCulture);
            }

        }
        internal static string tennesseeAvenue
        {
            get
            {
                return ResourceManager.GetString("tennesseeAvenue", resourceCulture);
            }

        }
        internal static string virginiaAvenue
        {
            get
            {
                return ResourceManager.GetString("virginiaAvenue", resourceCulture);
            }

        }
        internal static string statesAvenue
        {
            get
            {
                return ResourceManager.GetString("statesAvenue", resourceCulture);
            }

        }
        internal static string communityChest
        {
            get
            {
                return ResourceManager.GetString("communityChest", resourceCulture);
            }

        }
        internal static string waterWork
        {
            get
            {
                return ResourceManager.GetString("waterWork", resourceCulture);
            }

        }
        internal static string readingRailroad
        {
            get
            {
                return ResourceManager.GetString("waterWork", resourceCulture);
            }

        }
        internal static string Jail
        {
            get
            {
                return ResourceManager.GetString("Jail", resourceCulture);
            }

        }
        internal static string electricCompany
        {
            get
            {
                return ResourceManager.GetString("electricCompany", resourceCulture);
            }

        }
        internal static string pennRailroad
        {
            get
            {
                return ResourceManager.GetString("pennRailroad", resourceCulture);
            }

        }
        internal static string bo
        {
            get
            {
                return ResourceManager.GetString("bo", resourceCulture);
            }

        }
        internal static string shortLine
        {
            get
            {
                return ResourceManager.GetString("short", resourceCulture);
            }

        }
        internal static string toJ
        {
            get
            {
                return ResourceManager.GetString("toJ", resourceCulture);
            }

        }
        internal static string aGo
        {
            get
            {
                return ResourceManager.GetString("aGo", resourceCulture);
            }

        }
        internal static string Berror
        {
            get
            {
                return ResourceManager.GetString("Berror", resourceCulture);
            }

        }
        internal static string docF
        {
            get
            {
                return ResourceManager.GetString("docF", resourceCulture);
            }

        }
        internal static string outJ
        {
            get
            {
                return ResourceManager.GetString("outJ", resourceCulture);
            }

        }
        internal static string toJail
        {
            get
            {
                return ResourceManager.GetString("toJail", resourceCulture);
            }

        }
        internal static string bday
        {
            get
            {
                return ResourceManager.GetString("bday", resourceCulture);
            }

        }
        internal static string opNight
        {
            get
            {
                return ResourceManager.GetString("opNight", resourceCulture);
            }

        }
        internal static string inRe
        {
            get
            {
                return ResourceManager.GetString("inRe", resourceCulture);
            }

        }
        internal static string lifeIn
        {
            get
            {
                return ResourceManager.GetString("lifeIn", resourceCulture);
            }

        }
        internal static string hosp
        {
            get
            {
                return ResourceManager.GetString("hosp", resourceCulture);
            }

        }
        internal static string schoolF
        {
            get
            {
                return ResourceManager.GetString("schoolF", resourceCulture);
            }

        }
        internal static string consult
        {
            get
            {
                return ResourceManager.GetString("consult", resourceCulture);
            }

        }
        internal static string assess
        {
            get
            {
                return ResourceManager.GetString("assess", resourceCulture);
            }

        }
        internal static string beau
        {
            get
            {
                return ResourceManager.GetString("beau", resourceCulture);
            }

        }
        internal static string uncle
        {
            get
            {
                return ResourceManager.GetString("uncle", resourceCulture);
            }

        }
        internal static string stock
        {
            get
            {
                return ResourceManager.GetString("stock", resourceCulture);
            }

        }
        internal static string holi
        {
            get
            {
                return ResourceManager.GetString("holi", resourceCulture);
            }

        }
        internal static string poorTax
        {
            get
            {
                return ResourceManager.GetString("poorTax", resourceCulture);
            }

        }
        internal static string divi
        {
            get
            {
                return ResourceManager.GetString("divi", resourceCulture);
            }

        }
        internal static string aIlli
        {
            get
            {
                return ResourceManager.GetString("aIlli", resourceCulture);
            }

        }
        internal static string aNear
        {
            get
            {
                return ResourceManager.GetString("aNear", resourceCulture);
            }

        }
        internal static string aRail
        {
            get
            {
                return ResourceManager.GetString("aRail", resourceCulture);
            }

        }
        internal static string aSt
        {
            get
            {
                return ResourceManager.GetString("aSt", resourceCulture);
            }

        }
        internal static string goJail
        {
            get
            {
                return ResourceManager.GetString("aSt", resourceCulture);
            }

        }
        internal static string repair
        {
            get
            {
                return ResourceManager.GetString("repair", resourceCulture);
            }

        }
        internal static string tRead
        {
            get
            {
                return ResourceManager.GetString("tRead", resourceCulture);
            }

        }
        internal static string walk
        {
            get
            {
                return ResourceManager.GetString("walk", resourceCulture);
            }

        }
        internal static string chair
        {
            get
            {
                return ResourceManager.GetString("chair", resourceCulture);
            }

        }
        internal static string loan
        {
            get
            {
                return ResourceManager.GetString("loan", resourceCulture);
            }

        }
        internal static string cross
        {
            get
            {
                return ResourceManager.GetString("cross", resourceCulture);
            }

        }
    }
}
