//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monopoly {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monopoly.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Board.
        /// </summary>
        internal static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        internal static string chance {
            get {
                return ResourceManager.GetString("chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled Roll.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        internal static string endTurn {
            get {
                return ResourceManager.GetString("endTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string magProper {
            get {
                return ResourceManager.GetString("magProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P1.
        /// </summary>
        internal static string p1Label {
            get {
                return ResourceManager.GetString("p1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2.
        /// </summary>
        internal static string p2Label {
            get {
                return ResourceManager.GetString("p2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Fine.
        /// </summary>
        internal static string payFine {
            get {
                return ResourceManager.GetString("payFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        internal static string roll {
            get {
                return ResourceManager.GetString("roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income\r\nTax.
        /// </summary>
        internal static string taxLabel {
            get {
                return ResourceManager.GetString("taxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        internal static string trade {
            get {
                return ResourceManager.GetString("trade", resourceCulture);
            }
        }
    }
}
